name: molplat
channels:
- defaults
- conda-forge
dependencies:
- bzip2=1.0.8=h2bbff1b_6
- ca-certificates=2025.2.25=haa95532_0
- libffi=3.4.4=hd77b12b_1
- openssl=3.0.16=h3f729d1_0
- pip=25.1=pyhc872135_2
- python=3.11.8=he1021f5_0
- setuptools=78.1.1=py311haa95532_0
- sqlite=3.45.3=h2bbff1b_0
- tk=8.6.14=h5e9d12e_1
- vc=14.42=haa95532_5
- vs2015_runtime=14.42.34433=hbfb602d_5
- wheel=0.45.1=py311haa95532_0
- xz=5.6.4=h4754444_1
- zlib=1.2.13=h8cc25b3_1
- pip:
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.12.13
  - aiosignal==1.3.2
  - attrs==25.3.0
  - certifi==2025.6.15
  - charset-normalizer==3.4.2
  - contourpy==1.3.2
  - cycler==0.12.1
  - filelock==3.18.0
  - fonttools==4.58.4
  - frozenlist==1.7.0
  - fsspec==2025.5.1
  - huggingface-hub==0.33.1
  - idna==3.10
  - jinja2==3.1.6
  - joblib==1.5.1
  - kiwisolver==1.4.8
  - markupsafe==3.0.2
  - matplotlib==3.10.3
  - mpmath==1.3.0
  - multidict==6.5.1
  - networkx==3.5
  - numpy==2.3.1
  - packaging==25.0
  - pandas==2.3.0
  - pillow==11.2.1
  - propcache==0.3.2
  - pyparsing==3.2.3
  - pytz==2025.2
  - pyyaml==6.0.2
  - rdkit==2024.3.5
  - regex==2024.11.6
  - requests==2.32.4
  - safetensors==0.5.3
  - scikit-learn==1.7.0
  - scipy==1.16.0
  - seaborn==0.13.2
  - sympy==1.14.0
  - threadpoolctl==3.6.0
  - tokenizers==0.21.2
  - torch==2.7.1
  - torch-geometric==2.6.1
  - torch-scatter==2.1.2
  - tqdm==4.67.1
  - transformers==4.52.4
  - tzdata==2025.2
  - urllib3==2.5.0
  - xgboost==3.0.2
  - yarl==1.20.1
prefix: C:\Users\peter\anaconda3\envs\molplat
metadata:
  exported: '2025-07-26T00:03:08.783007'
  minimal: false
  pip_included: false
