datasets:
  BBBP:
    smiles_col: smiles
    label_cols: ["p_np"]
  Tox21:
    smiles_col: smiles
    label_cols: ["NR-AR", "NR-AR-LBD", "NR-AhR", "NR-Aromatase", "NR-ER", "NR-ER-LBD", "NR-PPAR-gamma", "SR-ARE", "SR-ATAD5", "SR-HSE", "SR-MMP", "SR-p53"]
  ClinTox:
    smiles_col: smiles
    label_cols: ["CT_TOX", "FDA_APPROVED"]
  HIV:
    smiles_col: smiles
    label_cols: ["HIV_active"]
  BACE:
    smiles_col: mol
    label_cols: ["Class"]
  MUV:
    smiles_col: smiles
    label_cols: [
      "MUV-466", "MUV-548", "MUV-600", "MUV-644", "MUV-652", "MUV-689", "MUV-692",
      "MUV-712", "MUV-713", "MUV-733", "MUV-737", "MUV-810", "MUV-832",
      "MUV-846", "MUV-852", "MUV-858", "MUV-859"
    ]
  SIDER:
    smiles_col: smiles
    label_cols: [
      "Hepatobiliary disorders", "Metabolism and nutrition disorders", "Product issues",
      "Eye disorders", "Investigations", "Musculoskeletal and connective tissue disorders",
      "Gastrointestinal disorders", "Social circumstances", "Immune system disorders",
      "Reproductive system and breast disorders",
      "Neoplasms benign, malignant and unspecified (incl cysts and polyps)",
      "General disorders and administration site conditions", "Endocrine disorders",
      "Surgical and medical procedures", "Vascular disorders",
      "Blood and lymphatic system disorders", "Skin and subcutaneous tissue disorders",
      "Congenital, familial and genetic disorders", "Infections and infestations",
      "Respiratory, thoracic and mediastinal disorders", "Psychiatric disorders",
      "Renal and urinary disorders", "Pregnancy, puerperium and perinatal conditions",
      "Ear and labyrinth disorders", "Cardiac disorders", "Nervous system disorders",
      "Injury, poisoning and procedural complications"
    ]
  FreeSolv:
    smiles_col: smiles
    label_cols: ["expt"]
  ESOL:
    smiles_col: smiles
    label_cols: ["measured log solubility in mols per litre"]
  Lipo:
    smiles_col: smiles
    label_cols: ["exp"]
  qm7:
    smiles_col: smiles
    label_cols: ["u0_atom"]
  qm8:
    smiles_col: smiles
    label_cols: ["E1-CC2", "E2-CC2", "f1-CC2", "f2-CC2", "E1-PBE0", "E2-PBE0", "f1-PBE0", "f2-PBE0", "E1-CAM", "E2-CAM", "f1-CAM", "f2-CAM"]
  qm9:
    smiles_col: smiles
    label_cols: ["mu", "alpha", "homo", "lumo", "gap", "r2", "zpve", "cv"]
