eval: true
model: FP_NN,FP_RF,FP_SVM,FP_XGB,GNN_GIN,GNN_GCN,RNN_RNN,SEQ_SEQ
name: BBBP,ESOL,ClinTox
output: results
plotpath: plots
plotprevisousruns: false
smiles_list: random20
target_list: all
user_argument: moleculenet
