eval: true
model: SEQ_SEQ,GNN_GCN,FP_SVM,FP_RF
name: BBBP,ClinTox,ESOL,FreeSolv,HIV,Lipo,MUV,SIDER,Tox21,qm7,qm8,qm9
output: results
plotpath: plots
plotprevisousruns: false
smiles_list: random20
target_list: all
user_argument: moleculenet
