base_config:
  device: cuda
  batch_size: 
    default: 128
    small: 32
  n_head: 12
  n_layer: 12
  n_embd: 768
  d_dropout: 0.1
  dropout: 0.1
  lr_start: 3e-5
  num_workers: 8
  max_epochs: 500
  num_feats: 32
  dims: [768 768 768 1]
  checkpoint_every: 100
  seed_path: '../data/Pretrained MoLFormer/checkpoints/N-Step-Checkpoint_3_30000.ckpt'

datasets:
  BBBP:
    data_root: '../data/bbbp'
    task_type: 'classification'
    targets: ['p_np']
    dims: [768, 768, 768, 1]
    batch_size: 128
    
  BACE:
    data_root: '../data/bace'
    task_type: 'classification'
    targets: ['Class']
    dims: [768, 768, 768, 1]
    batch_size: 128
    
  HIV:
    data_root: '../data/hiv'
    task_type: 'classification'
    targets: ['HIV_active']
    dims: [768, 768, 768, 1]
    batch_size: 32

  Tox21:
    data_root: '../data/tox21'
    task_type: 'multitask_classification'
    targets: ['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD', 
             'NR-PPAR-gamma', 'SR-ARE', 'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53']
    dims: [768, 768, 768, 1]
    batch_size: 128
    
  ClinTox:
    data_root: '../data/clintox'
    task_type: 'multitask_classification'
    targets: ['CT_TOX', 'FDA_APPROVED']
    dims: [768, 768, 768, 1]
    batch_size: 32
    
  SIDER:
    data_root: '../data/sider'
    task_type: 'multitask_classification'
    targets: [
      "Hepatobiliary disorders", "Metabolism and nutrition disorders", "Product issues",
      "Eye disorders", "Investigations", "Musculoskeletal and connective tissue disorders",
      "Gastrointestinal disorders", "Social circumstances", "Immune system disorders",
      "Reproductive system and breast disorders", 
      "Neoplasms benign, malignant and unspecified (incl cysts and polyps)",
      "General disorders and administration site conditions", "Endocrine disorders",
      "Surgical and medical procedures", "Vascular disorders",
      "Blood and lymphatic system disorders", "Skin and subcutaneous tissue disorders",
      "Congenital, familial and genetic disorders", "Infections and infestations",
      "Respiratory, thoracic and mediastinal disorders", "Psychiatric disorders",
      "Renal and urinary disorders", "Pregnancy, puerperium and perinatal conditions",
      "Ear and labyrinth disorders", "Cardiac disorders",
      "Nervous system disorders", "Injury, poisoning and procedural complications"
    ]
    dims: [768, 768, 768, 1]
    batch_size: 32

  FreeSolv:
    data_root: '../data/freesolv'
    task_type: 'regression'
    targets: ['expt']
    dims: [768, 768, 768, 1]
    
  ESOL:
    data_root: '../data/esol'
    task_type: 'regression'
    targets: ['measured log solubility in mols per litre']
    dims: [768, 768, 768, 1]
    
  qm9:
    data_root: '../data/qm9'
    task_type: 'regression'
    targets: ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'cv']
    dims: [768, 768, 768, 1]

run_settings:
  selected_datasets: ['qm9']
  selected_targets: {}
  max_parallel: 1
  log_level: 'INFO'
  save_progress: true
